allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  bufferutil: true
  canvas: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
