import { chromium } from 'playwright';
const BASE='https://staging.reglo.it', OUT='/tmp/hiro-design/reg-587';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:1000},locale:'it-IT'});
const p=await ctx.newPage();
await p.goto(`${BASE}/it/sign-in`,{waitUntil:'domcontentloaded'});
await p.fill('input[type="email"]','titolare@reglo.it'); await p.fill('input[type="password"]','RegloTest2026!');
await p.click('button[type="submit"]'); await p.waitForTimeout(7000);
await p.keyboard.press('Escape'); await p.waitForTimeout(600);
await p.mouse.click(1144,142); await p.waitForTimeout(1500);
await p.locator('text=Giorno').first().click(); await p.waitForTimeout(2500);
await p.mouse.click(263,217); await p.waitForTimeout(3000);
await p.locator('button', {hasText:'Alice Lombardi'}).first().click();
await p.waitForTimeout(1800);
await p.locator('text=Annulla guida').first().click();
await p.waitForTimeout(2500);
const dlg=p.locator('[role="dialog"]').last();
await dlg.screenshot({path:`${OUT}/01-domanda.png`});
console.log('titolo:', await p.evaluate(()=>document.querySelector('[role="dialog"] h2')?.textContent));
console.log('conferma disabilitata:', await p.evaluate(()=>{
  const d=document.querySelector('[role="dialog"]');
  const btn=Array.from(d.querySelectorAll('button')).find(b=>(b.textContent||'').trim()==='Annulla la guida');
  return btn?.disabled;
}));
// scegli "Dell'autoscuola" solo per lo screenshot dell'esito, poi torna su allievo
await p.locator('[role="dialog"] >> text=Dell\'autoscuola').first().click();
await p.waitForTimeout(1200);
await dlg.screenshot({path:`${OUT}/02-autoscuola.png`});
await p.locator('[role="dialog"] >> text=Dell\'allievo').first().click();
await p.waitForTimeout(1200);
await dlg.screenshot({path:`${OUT}/03-allievo.png`});
console.log('ok screenshot');
await b.close();
